version: "3.9"  #docker composeファイルのバージョン
services:
  app:  #任意のサービス名
    build: ./infra/php  #ビルドコンテキスト。docker buildを実行する際の作業ディレクトリ
    volumes:   #ホスト側のディレクトリ等をコンテナ側にマウント
      - ./src:/data #srcディレクトリをappコンテナの/dataへマウント
  web:
    # https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/#image
    image: nginx:1.20-alpine
    # https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/#ports
    ports:
      - 8080:80
    # https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/#volumes
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  # 以下、追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: